### ISSUE TITLE
Instructions don't work

### ISSUE THREAD

**Issue by nhathaway** [Hugolify/hugolify-sveltia-cms#1]
I get the following error:

Error: failed to load modules: module "github.com/hugolify/hugolify-sveltia-cms" not found in "[myproject]\\themes\\github.com\\hugolify\\hugolify-sveltia-cms"; either add it as a Hugo Module or store it in "[myproject]\\themes".: module does not exist

(where [myproject] is the path to my project)

**Comment by nhathaway** [comment]
It seems that you need 'go' (the compiler) installed first, then you do:

hugo mod init github.com/hugolify/hugolify-sveltia-cms

then you can add the config as per the instructions.

**Comment by sebousan** [comment]
Hi @nhathaway,
this is a repository for to use Sveltia CMS with Hugolify (Hugo framework).
You need first check documentation about Hugolify: https://www.hugolify.io/docs/getting-started/

Let me know if is OK for you.

Thanks
